spin_manifest_version = 2

[application]
authors = ["David Wallace Croft <david@CroftSoft.com>"]
description = "Prototype of a Fermyon Spin application"
name = "spin-prototype"
version = "0.0.0-SNAPSHOT"

[[trigger.http]]
component = "spin-prototype"
route = "/..."

[component.spin-prototype]
allowed_outbound_hosts = []
key_value_stores = ["default"]
source = "target/wasm32-wasi/release/spin_prototype.wasm"

[component.spin-prototype.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
